**Libraries**

In [ ]:
from pandas import DataFrame
import numpy as np
import itertools
from itertools import product
import matplotlib.pyplot as plt

## Datasets

### Input matrix generator

In [ ]:
def InputGenes(n):
    output = list(itertools.product([0, 1], repeat=n))
    return output

### Logic gates definition

In [ ]:
def AND(x, y):
  results = np.where(x!=y, 0, x)
  return results

In [ ]:
def OR(x, y):
  results = np.maximum(x, y)
  return results

In [ ]:
def NOT(x):
  results = np.where(x==0, 1, 0)
  return results

### The logical rules of the FOS-GRN

In [ ]:
X=InputGenes(13)
Y=InputGenes(13)

In [ ]:
X = DataFrame(X, columns=['AG','AP1','AP2','AP3','EMF1','FT','FUL','LFY','PI','SEP','TFL1','UFO','WUS'])
Y = DataFrame(Y, columns=['AG','AP1','AP2','AP3','EMF1','FT','FUL','LFY','PI','SEP','TFL1','UFO','WUS'])

In [ ]:
a0=AND(NOT(X["EMF1"]), AND(NOT(X["AP2"]),NOT(X["TFL1"])))
a1=AND(NOT(X["EMF1"]), AND(NOT(X["AP1"]),X["LFY"]))
a2=AND(NOT(X["EMF1"]), AND(NOT(X["AP2"]),X["LFY"]))
a3=AND(NOT(X["EMF1"]),AND(NOT(X["TFL1"]),AND(X["LFY"],AND(X["AG"],X["SEP"]))))
a4=AND(NOT(X["EMF1"]), AND(X["LFY"],X["WUS"]))

Y["AG"]=OR(OR(OR(OR(a0,a1),a2),a3),a4)

b0=AND(NOT(X["AG"]),NOT(X["TFL1"]))
b1=AND(X["FT"],AND(X["LFY"],NOT(X["AG"])))
b2=AND(X["FT"],AND(NOT(X["AG"]),NOT(X["PI"])))
b3=AND(X["LFY"],AND(NOT(X["AG"]),NOT(X["PI"])))
b4=AND(X["FT"],AND(NOT(X["AG"]),NOT(X["AP3"])))
b5=AND(X["LFY"],AND(NOT(X["AG"]),NOT(X["AP3"])))

Y["AP1"]=OR(OR(OR(OR(OR(b0,b1),b2),b3),b4),b5)

Y["AP2"]=NOT(X["TFL1"])

Y["AP3"]=OR(AND(X["LFY"],X["UFO"]),AND(X["PI"],AND(X["SEP"],AND(X["AP3"],OR(X["AG"],X["AP1"])))))

Y["EMF1"]=NOT(X["LFY"])

Y["FT"]=NOT(X["EMF1"])

Y["FUL"]=AND(NOT(X["AP1"]),NOT(X["TFL1"]))

Y["LFY"]=OR(NOT(X["EMF1"]),NOT(X["TFL1"]))

Y["PI"]=OR(AND(X["LFY"],OR(X["AG"],X["AP3"])),AND(X["PI"],AND(X["SEP"],AND(X["AP3"],OR(X["AG"],X["AP1"])))))

Y["SEP"]=X["LFY"]

Y["TFL1"]=AND(NOT(X["AP1"]),AND(X["EMF1"],NOT(X["LFY"])))

Y["UFO"]=X["UFO"]

Y["WUS"]=AND(X["WUS"],(OR(NOT(X["AG"]),NOT(X["SEP"]))))

#Training via perceptron

### AG

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["AG"])
  score = clf.score(X, Y["AG"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

AG_coef=best_coef
AG_intercept=best_intercept

0.98828125
[[  0.      -1.8928  -7.8928   0.     -19.8928   0.       0.      10.8928
    0.       0.      -5.8928   0.       1.8928]]
[3.]


### AP1

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["AP1"])
  score = clf.score(X, Y["AP1"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

AP1_coef=best_coef
AP1_intercept=best_intercept

1.0
[[-17.2656   0.       0.      -1.2656   0.       3.2656   0.       3.2656
   -1.2656   0.      -7.2656   0.       0.    ]]
[6.]


### AP2

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["AP2"])
  score = clf.score(X, Y["AP2"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

AP2_coef=best_coef
AP2_intercept=best_intercept

1.0
[[ 0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.     -1.2656  0.      0.    ]]
[1.]


### AP3

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["AP3"])
  score = clf.score(X, Y["AP3"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

AP3_coef=best_coef
AP3_intercept=best_intercept

0.9609375
[[0.2432 0.2432 0.     3.2432 0.     0.     0.     7.2432 1.2432 2.2432
  0.     6.2432 0.    ]]
[-13.]


### EMF1

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["EMF1"])
  score = clf.score(X, Y["EMF1"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

EMF1_coef=best_coef
EMF1_intercept=best_intercept

1.0
[[ 0.      0.      0.      0.      0.      0.      0.     -1.2656  0.
   0.      0.      0.      0.    ]]
[1.]


### FT

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["FT"])
  score = clf.score(X, Y["FT"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

FT_coef=best_coef
FT_intercept=best_intercept

1.0
[[ 0.      0.      0.      0.     -1.2656  0.      0.      0.      0.
   0.      0.      0.      0.    ]]
[1.]


### FUL

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["FUL"])
  score = clf.score(X, Y["FUL"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

FUL_coef=best_coef
FUL_intercept=best_intercept

1.0
[[ 0.     -1.2656  0.      0.      0.      0.      0.      0.      0.
   0.     -1.2656  0.      0.    ]]
[1.]


### LFY

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["LFY"])
  score = clf.score(X, Y["LFY"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

LFY_coef=best_coef
LFY_intercept=best_intercept

1.0
[[ 0.      0.      0.      0.     -3.2656  0.      0.      0.      0.
   0.     -3.2656  0.      0.    ]]
[6.]


### PI

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["PI"])
  score = clf.score(X, Y["PI"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

PI_coef=best_coef
PI_intercept=best_intercept

0.984375
[[ 6.1584  0.      0.     10.1584  0.      0.      0.     13.1584  2.1584
   2.1584  0.      0.      0.    ]]
[-19.]


### SEP

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["SEP"])
  score = clf.score(X, Y["SEP"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

SEP_coef=best_coef
SEP_intercept=best_intercept

1.0
[[0.     0.     0.     0.     0.     0.     0.     1.2656 0.     0.
  0.     0.     0.    ]]
[-1.]


### TFL1

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["TFL1"])
  score = clf.score(X, Y["TFL1"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

TFL1_coef=best_coef
TFL1_intercept=best_intercept

1.0
[[ 0.     -0.2656  0.      0.      1.2656  0.      0.     -0.2656  0.
   0.      0.      0.      0.    ]]
[-1.]


### UFO

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["UFO"])
  score = clf.score(X, Y["UFO"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

UFO_coef=best_coef
UFO_intercept=best_intercept

1.0
[[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     1.2656 0.    ]]
[-1.]


### WUS

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
small_weights = 1000

for i in range(0,100):
  clf = Perceptron(penalty='l1', random_state=i)
  clf.fit(X, Y["WUS"])
  score = clf.score(X, Y["WUS"])
  weights = np.sum(abs(clf.coef_))
  if ((score >= best_score) and (small_weights > weights)):
    best_score = score
    small_weights = weights
    best_coef=clf.coef_
    best_intercept=clf.intercept_
    best_state = i

print(best_score)
print(best_coef)
print(best_intercept)

WUS_coef=best_coef
WUS_intercept=best_intercept

1.0
[[-1.2656  0.      0.      0.      0.      0.      0.      0.      0.
  -0.2656  0.      0.      4.2656]]
[-3.]


### Assembling the weight matrix

In [ ]:
Weight_matrix = np.vstack((AG_coef,AP1_coef,AP2_coef,AP3_coef,EMF1_coef,FT_coef,FUL_coef,LFY_coef,PI_coef,SEP_coef,TFL1_coef,UFO_coef,WUS_coef))
Weight_matrix.shape

(13, 13)

In [ ]:
Weight_matrix

array([[  0.    ,  -1.8928,  -7.8928,   0.    , -19.8928,   0.    ,
          0.    ,  10.8928,   0.    ,   0.    ,  -5.8928,   0.    ,
          1.8928],
       [-17.2656,   0.    ,   0.    ,  -1.2656,   0.    ,   3.2656,
          0.    ,   3.2656,  -1.2656,   0.    ,  -7.2656,   0.    ,
          0.    ],
       [  0.    ,   0.    ,   0.    ,   0.    ,   0.    ,   0.    ,
          0.    ,   0.    ,   0.    ,   0.    ,  -1.2656,   0.    ,
          0.    ],
       [  0.2432,   0.2432,   0.    ,   3.2432,   0.    ,   0.    ,
          0.    ,   7.2432,   1.2432,   2.2432,   0.    ,   6.2432,
          0.    ],
       [  0.    ,   0.    ,   0.    ,   0.    ,   0.    ,   0.    ,
          0.    ,  -1.2656,   0.    ,   0.    ,   0.    ,   0.    ,
          0.    ],
       [  0.    ,   0.    ,   0.    ,   0.    ,  -1.2656,   0.    ,
          0.    ,   0.    ,   0.    ,   0.    ,   0.    ,   0.    ,
          0.    ],
       [  0.    ,  -1.2656,   0.    ,   0.    ,   0.    ,   0.    ,
  

### Assembling the threshold vector

In [ ]:
Theta = np.hstack((AG_intercept,AP1_intercept,AP2_intercept,AP3_intercept,EMF1_intercept,FT_intercept,FUL_intercept,LFY_intercept,PI_intercept,SEP_intercept,TFL1_intercept,UFO_intercept,WUS_intercept))
Theta = -Theta
print(Theta)

[-3. -6. -1. 13. -1. -1. -1. -6. 19.  1.  1.  1.  3.]


### Threshold Boolean network updating rule

In [ ]:
def evaluateModel(W,Th,Ig):
  res=np.zeros(len(Ig))
  aux=np.dot(W,Ig)
  aux1=aux-Th
  aux1=aux1.flatten()
  for j in range(0,len(Ig)):
    if aux1[j]>0:
      res[j]=1
    else:
      res[j]=0
  return (res)

In [ ]:
def evaluateModelN(W,Th,k):
  z=len(W)
  Ig=np.array(InputGenes(z))
  output=Ig
  for j in range(0,k):
    for i in range(0, len(Ig)):
      output[i,:]=evaluateModel(W,Th,output[i,:])
  return (output)

### Perform one update of the threshold Boolean network

In [ ]:
Y1=evaluateModelN(Weight_matrix,Theta,1)

### How many fixed points?

In [ ]:
erroraux=np.sum(np.all(X == Y1, axis=1))
print(erroraux)

7


### Which ones are they?

In [ ]:
FPs1=np.all(X == Y1, axis=1)

In [ ]:
np.where(FPs1==True)

(array([ 260,  261,  262,  263, 5368, 5880, 5882]),)

In [ ]:
X = np.array(X)

#### state 260

In [ ]:
X[260,:]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

This corresponds to INF1

#### state 261

In [ ]:
X[261,:]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1])

This corresponds to INF3

#### state 262

In [ ]:
X[262,:]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0])

This corresponds to INF2

#### state 263

In [ ]:
X[263,:]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

This corresponds to INF4

#### state 5368

In [ ]:
X[5368,:]

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0])

This corresponds to CAR

#### state 5880

In [ ]:
X[5880,:]

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0])

This corresponds to STM2

#### state 5882

In [ ]:
X[5882,:]

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0])

This corresponds to STM1

### What are the missing fixed points

In [ ]:
FPs=np.all(X == Y, axis=1)

In [ ]:
np.where(FPs==True)

(array([ 260,  261,  262,  263, 3240, 3768, 3770, 5368, 5880, 5882]),)

#### state 3240

In [ ]:
X[3240,:]

array([0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0])

This corresponds to SEP

#### state 3768

In [ ]:
X[3768,:]

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0])

This corresponds to PET2

#### state 3770

In [ ]:
X[3770,:]

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0])

This corresponds to PET1

In [ ]:
X.shape

(8192, 13)

## New input matrix containig only the original 10 fixed points

In [ ]:
row_indices = np.where(FPs==True)
X_new=X[row_indices]
X_new.shape

(10, 13)

### Since they are fixed points, the corresponding rows in Y should be the same

In [ ]:
Y=np.array(Y)
Y_new=Y[row_indices]
Y_new.shape

(10, 13)

In [ ]:
X_new==Y_new

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,

In [ ]:
X_new = DataFrame(X_new, columns=['AG','AP1','AP2','AP3','EMF1','FT','FUL','LFY','PI','SEP','TFL1','UFO','WUS'])
Y_new = DataFrame(Y_new, columns=['AG','AP1','AP2','AP3','EMF1','FT','FUL','LFY','PI','SEP','TFL1','UFO','WUS'])

# Lets train the perceptrons with only X_new and Y_new

In [ ]:
X=InputGenes(13)
Y=InputGenes(13)

In [ ]:
X = DataFrame(X, columns=['AG','AP1','AP2','AP3','EMF1','FT','FUL','LFY','PI','SEP','TFL1','UFO','WUS'])
Y = DataFrame(Y, columns=['AG','AP1','AP2','AP3','EMF1','FT','FUL','LFY','PI','SEP','TFL1','UFO','WUS'])

In [ ]:
a0=AND(NOT(X["EMF1"]), AND(NOT(X["AP2"]),NOT(X["TFL1"])))
a1=AND(NOT(X["EMF1"]), AND(NOT(X["AP1"]),X["LFY"]))
a2=AND(NOT(X["EMF1"]), AND(NOT(X["AP2"]),X["LFY"]))
a3=AND(NOT(X["EMF1"]),AND(NOT(X["TFL1"]),AND(X["LFY"],AND(X["AG"],X["SEP"]))))
a4=AND(NOT(X["EMF1"]), AND(X["LFY"],X["WUS"]))

Y["AG"]=OR(OR(OR(OR(a0,a1),a2),a3),a4)

b0=AND(NOT(X["AG"]),NOT(X["TFL1"]))
b1=AND(X["FT"],AND(X["LFY"],NOT(X["AG"])))
b2=AND(X["FT"],AND(NOT(X["AG"]),NOT(X["PI"])))
b3=AND(X["LFY"],AND(NOT(X["AG"]),NOT(X["PI"])))
b4=AND(X["FT"],AND(NOT(X["AG"]),NOT(X["AP3"])))
b5=AND(X["LFY"],AND(NOT(X["AG"]),NOT(X["AP3"])))

Y["AP1"]=OR(OR(OR(OR(OR(b0,b1),b2),b3),b4),b5)

Y["AP2"]=NOT(X["TFL1"])

Y["AP3"]=OR(AND(X["LFY"],X["UFO"]),AND(X["PI"],AND(X["SEP"],AND(X["AP3"],OR(X["AG"],X["AP1"])))))

Y["EMF1"]=NOT(X["LFY"])

Y["FT"]=NOT(X["EMF1"])

Y["FUL"]=AND(NOT(X["AP1"]),NOT(X["TFL1"]))

Y["LFY"]=OR(NOT(X["EMF1"]),NOT(X["TFL1"]))

Y["PI"]=OR(AND(X["LFY"],OR(X["AG"],X["AP3"])),AND(X["PI"],AND(X["SEP"],AND(X["AP3"],OR(X["AG"],X["AP1"])))))

Y["SEP"]=X["LFY"]

Y["TFL1"]=AND(NOT(X["AP1"]),AND(X["EMF1"],NOT(X["LFY"])))

Y["UFO"]=X["UFO"]

Y["WUS"]=AND(X["WUS"],(OR(NOT(X["AG"]),NOT(X["SEP"]))))

### AG

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
best_score_global=0
small_weights = 1000

for i in range(0,100):
  clf_new = Perceptron(penalty='l1', random_state=i)
  clf_new.fit(X_new, Y_new["AG"])
  score = clf_new.score(X_new, Y_new["AG"])
  score_global = clf_new.score(X, Y["AG"])
  weights = np.sum(abs(clf_new.coef_))
  if ((score >= best_score) and (small_weights > weights) and (score_global >= best_score_global) ):
    best_score = score
    best_score_global = score_global
    small_weights = weights
    best_coef=clf_new.coef_
    best_intercept=clf_new.intercept_
    best_state = i

print(best_score)
print(best_score_global)
print(best_coef)
print(best_intercept)

AG_coef_new=best_coef
AG_intercept_new=best_intercept

1.0
0.736328125
[[ 0.993 -0.993  0.     0.    -0.993  0.     0.993  0.     0.     0.
  -0.993  0.993  0.   ]]
[-1.]


### AP3

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
best_score_global=0
small_weights = 1000

for i in range(0,100):
  clf_new = Perceptron(penalty='l1', random_state=i)
  clf_new.fit(X_new, Y_new["AP3"])
  score = clf_new.score(X_new, Y_new["AP3"])
  score_global = clf_new.score(X, Y["AP3"])
  weights = np.sum(abs(clf_new.coef_))
  if ((score >= best_score) and (small_weights > weights)and (score_global >= best_score_global)):
    best_score = score
    best_score_global = score_global
    small_weights = weights
    best_coef=clf_new.coef_
    best_intercept=clf_new.intercept_
    best_state = i

print(best_score)
print(best_score_global)
print(best_coef)
print(best_intercept)

AP3_coef_new=best_coef
AP3_intercept_new=best_intercept

1.0
0.70703125
[[ 0.     0.     0.     0.993 -0.993  0.     0.     0.     0.993  0.
  -0.993  0.993  0.   ]]
[-1.]


### PI

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np

best_score = 0
best_score_global=0
small_weights = 1000

for i in range(0,100):
  clf_new = Perceptron(penalty='l1', random_state=i)
  clf_new.fit(X_new, Y_new["PI"])
  score = clf_new.score(X_new, Y_new["PI"])
  score_global = clf_new.score(X, Y["PI"])
  weights = np.sum(abs(clf_new.coef_))
  if ((score >= best_score) and (small_weights > weights)and (score_global >= best_score_global)):
    best_score = score
    best_score_global = score_global
    small_weights = weights
    best_coef=clf_new.coef_
    best_intercept=clf_new.intercept_
    best_state = i

print(best_score)
print(best_score_global)
print(best_coef)
print(best_intercept)

PI_coef_new=best_coef
PI_intercept_new=best_intercept

1.0
0.640625
[[ 0.     0.     0.     1.992 -0.992  0.     0.     0.     1.992  0.
  -0.992  0.     0.   ]]
[-1.]


In [ ]:
Weight_matrix_new2 = np.vstack((AG_coef_new,AP1_coef,AP2_coef,AP3_coef_new,EMF1_coef,FT_coef,FUL_coef,LFY_coef,PI_coef_new,SEP_coef,TFL1_coef,UFO_coef,WUS_coef))

In [ ]:
Theta_new2 = np.hstack((AG_intercept_new,AP1_intercept,AP2_intercept,AP3_intercept_new,EMF1_intercept,FT_intercept,FUL_intercept,LFY_intercept,PI_intercept_new,SEP_intercept,TFL1_intercept,UFO_intercept,WUS_intercept))
Theta_new2 = -Theta_new2
print(Theta_new2)

[ 1. -6. -1.  1. -1. -1. -1. -6.  1.  1.  1.  1.  3.]


In [ ]:
Y2_new=evaluateModelN(Weight_matrix_new2,Theta_new2,1)

In [ ]:
erroraux=np.sum(np.all(X == Y2_new, axis=1))
print(erroraux)

19


### Which ones are they?

In [ ]:
FPs1_new2=np.all(X == Y2_new, axis=1)

In [ ]:
Y2_new.shape

(8192, 13)

In [ ]:
np.where(FPs1_new2==True)

(array([ 260,  261,  262,  263, 3240, 3241, 3242, 3243, 3256, 3257, 3768,
        3769, 3770, 3771, 5352, 5354, 5368, 5880, 5882]),)

In [ ]:
(array([ 260,  261,  262,  263, 3240, 3768, 3770, 5368, 5880, 5882]),)